### PR TITLE
Pulling in the magic strings from an online source

### PR DESCRIPTION
**Pull request by noelmarkham**
This parses the data in the "big list of naughty strings" repo and provides a generator.

Originally I was trying to use a macro to parse the lines into a list, and I realised I didn't really need to do that :-/  ... I think the rationale behind that was to only have that list parsed once ever - at library compile time - but it wasn't really worth the effort when it can be done so simply when the Magic class is first referenced, I think this is a fine tradeoff.

@juanpedromoreno @fedefernandez what do you think?

### CODE REVIEW

**Comment by fedefernandez** [comment]
I'm okay with this approach.
Do you think it would need to be defined as `lazy`?
On the other hand, I'm not sure if the magic file will be packaged inside the jar

**Comment by noelmarkham** [comment]
I don't think lazy is necessary - if anything that's going the opposite way to which I'd want to go (ideally I want the list parsed at compile time as this only ever needs to be done once).

As for in the Jar, I assumed it would be as it's in the `resources` directory, but this is something that I should definitely test. Thanks!

**Comment by noelmarkham** [comment]
I've manually tested this and it works fine in a fresh project, pulling in the published Jar. I've created issue #55 to do the work to automate this.

If you're happy can I get a LGTM and I'll merge this.

Thanks!

**Comment by fedefernandez** [comment]
Should it be Scala 2.10 and 2.11 compatible? The method `fromResource` is only available from Scala 2.12

**Comment by noelmarkham** [comment]
Ah yes, this is masked by the multiple build issues I was planning to fix after this. I'm going to mark this PR as blocked until I've fixed #52

**Comment by noelmarkham** [comment]
@fedefernandez are you able to review now please? This is working across Scala 2.[10, 11, 12].

Thanks

**Pull request merged**
